name: Check DRL 15m

on:
  schedule:
    - cron: '*/15 * * * *' # Chạy tự động mỗi 15 phút

jobs:
  run-bot:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Set up Python
           uses: actions/setup-python@v5
           with:
             python-version: '3.10'
         - name: Install dependencies
           run: pip install requests beautifulsoup4
         - name: Run script
           env:
             TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
             TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
           python: python bot.py
           run: python bot.py
           
